-- -------------------------------------------------------------
-- 
-- File Name: hdl_prj\hdlsrc\pulse_detector_v4_4\MATLAB_Function.vhd
-- Created: 2022-07-05 22:17:10
-- 
-- Generated by MATLAB 9.3 and HDL Coder 3.11
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: MATLAB_Function
-- Source Path: pulse_detector_v4_4/Pulse Detector/Local Peak/MATLAB Function
-- Hierarchy Level: 2
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Pulse_Detector_pkg.ALL;

ENTITY MATLAB_Function IS
  PORT( DataBuff                          :   IN    vector_of_std_logic_vector18(0 TO 10);  -- sfix18_En11 [11]
        threshold                         :   IN    std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        MidSample                         :   OUT   std_logic_vector(17 DOWNTO 0);  -- sfix18_En11
        detected                          :   OUT   std_logic
        );
END MATLAB_Function;


ARCHITECTURE rtl OF MATLAB_Function IS

  -- Functions
  -- HDLCODER_TO_STDLOGIC 
  FUNCTION hdlcoder_to_stdlogic(arg: boolean) RETURN std_logic IS
  BEGIN
    IF arg THEN
      RETURN '1';
    ELSE
      RETURN '0';
    END IF;
  END FUNCTION;


  -- Signals
  SIGNAL DataBuff_signed                  : vector_of_signed18(0 TO 10);  -- sfix18_En11 [11]
  SIGNAL threshold_signed                 : signed(17 DOWNTO 0);  -- sfix18_En11
  SIGNAL MidSample_tmp                    : signed(17 DOWNTO 0);  -- sfix18_En11

BEGIN
  outputgen: FOR k1 IN 0 TO 10 GENERATE
    DataBuff_signed(k1) <= signed(DataBuff(k1));
  END GENERATE;

  threshold_signed <= signed(threshold);

  MATLAB_Function_1_output : PROCESS (DataBuff_signed, threshold_signed)
    VARIABLE CompareOut : vector_of_signed19(0 TO 10);
    VARIABLE c : std_logic_vector(0 TO 10);
    VARIABLE y : std_logic;
    VARIABLE extend_temp : signed(18 DOWNTO 0);
    VARIABLE sub_cast : vector_of_signed19(0 TO 10);
  BEGIN
    -- Sliding window operation
    -- Compare each value in the window to the middle sample via subtraction
    extend_temp := resize(DataBuff_signed(5), 19);
    -- this is a vector
    -- if all values in the result are negative and the middle sample is
    -- greater than a threshold, it is a local max
    y := '1';

    FOR k IN 0 TO 10 LOOP
      sub_cast(k) := resize(DataBuff_signed(k), 19);
      CompareOut(k) := sub_cast(k) - extend_temp;
      IF CompareOut(k) <= to_signed(16#00000#, 19) THEN 
        c(k) := '1';
      ELSE 
        c(k) := '0';
      END IF;
      y := y AND c(k);
    END LOOP;

    detected <= y AND hdlcoder_to_stdlogic(DataBuff_signed(5) > threshold_signed);
    MidSample_tmp <= DataBuff_signed(5);
  END PROCESS MATLAB_Function_1_output;


  MidSample <= std_logic_vector(MidSample_tmp);

END rtl;

